### ISSUE TITLE
Releassing `circuit-notation`

### ISSUE THREAD

**Issue by martijnbastiaan** [cchalmers/circuit-notation#24]
@cchalmers At some point I want to release `clash-protocols`, which would need to have `circuit-notation` on Hackage too. Would you be fine with me putting a release on Hackage? I'll add you as a maintainer of course.

**Comment by cchalmers** [comment]
Sure. I'll try to get to it some time this week.

**Comment by cchalmers** [comment]
Turns out a was very busy last week but I did the release today: https://hackage.haskell.org/package/circuit-notation-0.1.0.0. Let me know if there's any issues.

I've also added QBayLogic as a maintainer. Feel free to push bug fixes etc.

**Comment by martijnbastiaan** [comment]
Thanks!
